version: '3.8'

services:
  producer:
    build: ./producer
    ports:
      - "8001:8001"
    depends_on:
      - rabbitmq

  health_check_consumer:
    build: ./consumer_one
    depends_on:
      - rabbitmq

  item_creation_consumer:
    build: ./consumer_two
    depends_on:
      - rabbitmq

  stock_management_consumer:
    build: ./consumer_three
    depends_on:
      - rabbitmq

  order_processing_consumer:
    build: ./consumer_four
    depends_on:
      - rabbitmq

  database:
    build: ./database
    ports:
      - "27017:27017"

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"

networks:
  default:
    external:
      name: rabbitmq-network
